version: '3'

# development overrides
services:
    bigquery-views-manager:
        environment:
            GOOGLE_CLOUD_PROJECT: bigquery-views-manager
        volumes:
            - ~/.config/gcloud:/root/.config/gcloud
            - ./example-data:/opt/bigquery-views-manager/example-data
