version: '3'

# to add images that are only used for tests and by Jenkins in general
services:
    bigquery-views:
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json
        volumes:
            - ./credentials.json:/tmp/credentials.json
