version: '3'

# development overrides
services:
    bigquery-views:
        environment:
            GOOGLE_CLOUD_PROJECT: bigquery-views-manager
        volumes:
            - ~/.config/gcloud:/root/.config/gcloud
            - ./example-data:/tmp/example-data
