name: CI Build

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches:
      - develop
env:
  DATASET_NAME: bigquery_views_manager_ci
  DOCKER_COMPOSE_CI: docker compose -f docker-compose.yml -f docker-compose.ci.yml

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build Image and Run Tests
        run: make ci-build-and-test DOCKER_COMPOSE_CI='${{ env.DOCKER_COMPOSE_CI }}'
      - name: Setup GCP Secrets
        run: echo -n '${{ secrets.BIGQUERY_VIEWS_MANAGER_GCP_TEST }}' > ./credentials.json
      - name: Clean dataset
        run: make DOCKER_COMPOSE_CI='${{ env.DOCKER_COMPOSE_CI }}' IMAGE_TAG=${{ github.sha }} REVISION=${{ github.sha }} DATASET_NAME=${{ env.DATASET_NAME }} ci-example-data-clean-dataset
